AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description:
  Node.js barebone for AWS Lambda
Globals:
  Function:
    Timeout: 300
    Runtime: nodejs14.x
    MemorySize: 512
Resources:
  MainSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "MainSNSTopic"
  MainFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MainProcessorFunction
      CodeUri: "src"
      Handler: index.handleEvent
      ReservedConcurrentExecutions: 5
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref MainSNSTopic
